=== ministryofjustice/laa-court-data-adaptor/lib/schemas/api/progression.query.laa.application-laa.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/progression/query/laa/application-laa.json",
  "type": "object",
  "properties": {
    "applicationId": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "applicationReference": {
      "description": "The LAA issued reference to the application.  Currently known as the MAAT Id",
      "type": "string"
    },
    "applicationStatus": {
      "description": "Indicates if the application is draft, listed or finalised",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/courtApplicationStatus"
    },
    "applicationTitle": {
      "description": "The CJS Title for the court application type",
      "type": "string"
    },
    "applicationType": {
      "description": "The value of the Application.type.type",
      "type": "string"
    },
    "receivedDate": {
      "type": "string",
      "format": "date"
    },
    "judicialResults": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://justice.gov.uk/core/courts/external/apiJudicialResult.json"
      }
    },
    "caseSummary": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "id": "http://justice.gov.uk/progression/query/laa/case-summary.json",
          "properties": {
            "caseStatus": {
              "type": "string"
            },
            "prosecutionCaseId": {
              "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
            },
            "prosecutionCaseReference": {
              "description": "The URN or PRN of the case",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "hearingSummary": {
      "type": "array",
      "items": [
        {
          "id": "http://justice.gov.uk/progression/query/laa/hearing-summary.json",
          "type": "object",
          "properties": {
            "hearingId": {
              "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
            },
            "jurisdictionType": {
              "type": "string"
            },
            "estimatedDuration": {
              "type": "string"
            },
            "defendantIds": {
              "type": "array",
              "items": [
                {
                  "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                }
              ]
            },
            "hearingType": {
              "type": "object",
              "id": "http://justice.gov.uk/progression/query/laa/hearing-type.json",
              "properties": {
                "id": {
                  "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                },
                "description": {
                  "type": "string"
                },
                "code": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "description"
              ],
              "additionalProperties": false
            },
            "courtCentre": {
              "id": "http://justice.gov.uk/progression/query/laa/court-centre.json",
              "type": "object",
              "properties": {
                "id": {
                  "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                },
                "code": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "roomId": {
                  "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                },
                "roomName": {
                  "type": "string"
                },
                "welshName": {
                  "type": "string"
                },
                "welshRoomName": {
                  "type": "string"
                },
                "address": {
                  "id": "http://justice.gov.uk/progression/query/laa/address.json",
                  "type": "object",
                  "properties": {
                    "address1": {
                      "type": "string"
                    },
                    "address2": {
                      "type": "string"
                    },
                    "address3": {
                      "type": "string"
                    },
                    "address4": {
                      "type": "string"
                    },
                    "postCode": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "address1",
                    "postCode"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "id",
                "name",
                "roomId",
                "roomName"
              ],
              "additionalProperties": false
            },
            "hearingDay": {
              "type": "array",
              "items": [
                {
                  "id": "http://justice.gov.uk/progression/query/laa/hearing-day.json",
                  "type": "object",
                  "properties": {
                    "sittingDay": {
                      "type": "string"
                    },
                    "listingSequence": {
                      "type": "integer"
                    },
                    "listedDurationMinutes": {
                      "type": "integer"
                    },
                    "hasSharedResults": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "sittingDay"
                  ],
                  "additionalProperties": false
                }
              ]
            },
            "defenceCounsel": {
              "type": "array",
              "items": [
                {
                  "id": "http://justice.gov.uk/progression/query/laa/defence-counsel.json",
                  "type": "object",
                  "properties": {
                    "id": {
                      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                    },
                    "title": {
                      "type": "string"
                    },
                    "firstName": {
                      "type": "string"
                    },
                    "middleName": {
                      "type": "string"
                    },
                    "lastName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "defendants": {
                      "type": "array",
                      "items": [
                        {
                          "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                        }
                      ]
                    },
                    "attendanceDays": {
                      "type": "array",
                      "items": [
                        {
                          "type": "string"
                        }
                      ]
                    }
                  },
                  "additionalProperties": false
                }
              ]
            }
          },
          "required": [
            "hearingId",
            "hearingType",
            "courtCentre",
            "hearingDay"
          ],
          "additionalProperties": false
        }
      ]
    },
    "subjectSummary":  {
      "id": "http://justice.gov.uk/progression/query/laa/subject-summary.json",
      "type": "object",
      "properties": {
        "proceedingsConcluded": {
          "type": "boolean"
        },
        "subjectId": {
          "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
        },
        "masterDefendantId": {
          "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
        },
        "defendantASN": {
          "type": "string"
        },
        "defendantFirstName": {
          "type": "string"
        },
        "defendantMiddleName": {
          "type": "string"
        },
        "defendantLastName": {
          "type": "string"
        },
        "defendantDOB": {
          "type": "string"
        },
        "defendantNINO": {
          "type": "string"
        },
        "dateOfNextHearing": {
          "type": "string"
        },
        "representationOrder": {
          "id": "http://justice.gov.uk/progression/query/laa/representation-order.json",
          "type": "object",
          "properties": {
            "applicationReference": {
              "type": "string"
            },
            "effectiveFromDate": {
              "type": "string",
              "format": "date"
            },
            "effectiveToDate": {
              "type": "string",
              "format": "date"
            },
            "laaContractNumber": {
              "type": "string"
            }
          },
          "required": [
            "applicationReference"
          ],
          "additionalProperties": false
        },
        "offenceSummary": {
          "type": "array",
          "items": [
            {
              "id": "http://justice.gov.uk/progression/query/laa/offence-summary.json",
              "type": "object",
              "properties": {
                "offenceId": {
                  "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
                },
                "offenceCode": {
                  "type": "string"
                },
                "offenceTitle": {
                  "type": "string"
                },
                "offenceLegislation": {
                  "type": "string"
                },
                "proceedingsConcluded": {
                  "type": "boolean"
                },
                "arrestDate": {
                  "type": "string"
                },
                "dateOfInformation": {
                  "type": "string"
                },
                "endDate": {
                  "type": "string"
                },
                "startDate": {
                  "type": "string"
                },
                "chargeDate": {
                  "type": "string"
                },
                "modeOfTrial": {
                  "type": "string"
                },
                "orderIndex": {
                  "type": "integer"
                },
                "wording": {
                  "type": "string"
                },
                "laaApplnReference": {
                  "id": "http://justice.gov.uk/progression/query/laa/laa-appln-reference.json",
                  "type": "object",
                  "properties": {
                    "applicationReference": {
                      "type": "string"
                    },
                    "statusId": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "string"
                    },
                    "statusDescription": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "applicationReference",
                    "statusId",
                    "statusCode",
                    "statusDescription"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "offenceId",
                "offenceCode",
                "offenceTitle",
                "offenceLegislation",
                "proceedingsConcluded",
                "arrestDate",
                "startDate",
                "chargeDate",
                "modeOfTrial",
                "orderIndex",
                "wording"
              ],
              "additionalProperties": false
            }
          ]
        }
      },
      "required": [
        "subjectId",
        "defendantFirstName"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "applicationId",
    "applicationReference",
    "applicationStatus"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/court_application_details/all_fields.json
{
    "applicationId": "4362f2bc-7aff-462a-a242-0db421aa6a96",
    "applicationReference": "RQ249717027",
    "applicationStatus": "FINALISED",
    "applicationTitle": "Appeal against conviction by a Magistrates' Court to the Crown Court",
    "applicationType": "MC80802",
    "caseSummary": [
        {
            "caseStatus": "ACTIVE",
            "prosecutionCaseId": "78307605-1521-466a-b964-67675887f604",
            "prosecutionCaseReference": "RQ249717027"
        }
    ],
    "hearingSummary": [
        {
            "courtCentre": {
                "address": {
                    "address1": "176A Lavender Hill",
                    "address2": "London",
                    "address3": "",
                    "address4": "",
                    "postCode": "SW11 1JU"
                },
                "code": "B01LY00",
                "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
                "name": "Lavender Hill Magistrates' Court",
                "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
                "roomName": "Courtroom 01"
            },
            "defendantIds": [
                "a86c42dc-6566-4076-9655-b3a53cd58566"
            ],
            "hearingDay": [
                {
                    "hasSharedResults": true,
                    "listedDurationMinutes": 1,
                    "listingSequence": 0,
                    "sittingDay": "2025-02-07T10:00:00.000Z"
                }
            ],
            "hearingId": "769d0056-e160-4aa9-a9d1-821db73aa1ee",
            "hearingType": {
                "description": "Application",
                "id": "3449743b-95d6-4836-8941-57f588b52068"
            },
            "jurisdictionType": "MAGISTRATES"
        }
    ],
    "judicialResults": [
        {
            "alwaysPublished": false,
            "canBeSubjectOfBreach": false,
            "canBeSubjectOfVariation": false,
            "category": "FINAL",
            "cjsCode": "1017",
            "courtClerk": {
                "firstName": "Erica",
                "lastName": "Wilson",
                "userId": "a085e359-6069-4694-8820-7810e7dfe762"
            },
            "d20": false,
            "dvlaCode": "J",
            "excludedFromResults": false,
            "isAdjournmentResult": false,
            "isAvailableForCourtExtract": true,
            "isConvictedResult": true,
            "isDeleted": false,
            "isFinancialResult": false,
            "isNewAmendment": true,
            "isUnscheduled": false,
            "judicialResultId": "1755ac43-585b-49d0-bdcc-e763d4a17c6c",
            "judicialResultTypeId": "b9c6047b-fb84-4b12-97a1-2175e4b8bbac",
            "label": "Absolute discharge",
            "lastSharedDateTime": "2025-02-06",
            "level": "O",
            "lifeDuration": false,
            "orderedDate": "2025-02-07",
            "orderedHearingId": "769d0056-e160-4aa9-a9d1-821db73aa1ee",
            "policeSubjectLineTitle": "Final Sentence",
            "postHearingCustodyStatus": "A",
            "preserveActiveOrder": false,
            "publishedAsAPrompt": false,
            "publishedForNows": false,
            "rank": 53800,
            "resultText": "AD - Absolute discharge",
            "resultWording": "",
            "rollUpPrompts": true,
            "rootJudicialResultId": "1755ac43-585b-49d0-bdcc-e763d4a17c6c",
            "rootJudicialResultTypeId": "b9c6047b-fb84-4b12-97a1-2175e4b8bbac",
            "terminatesOffenceProceedings": false,
            "urgent": false,
            "usergroups": [],
            "welshLabel": "Rhyddhad diamod"
        }
    ],
    "receivedDate": "2025-02-06",
    "subjectSummary": {
        "dateOfNextHearing": "2025-02-07T10:00:00.000Z",
        "defendantASN": "2391NX0000489661589D",
        "defendantDOB": "1999-02-06",
        "defendantFirstName": "Naida",
        "defendantLastName": "Daniel",
        "masterDefendantId": "a86c42dc-6566-4076-9655-b3a53cd58566",
        "offenceSummary": [],
        "proceedingsConcluded": false,
        "subjectId": "4b463e6a-105b-433b-a88d-057d6e645bfb"
    }
}
