=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/apiAllocationDecision.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiAllocationDecision.json",
  "description": "The allocation decision made regarding the jurisdiction required or elected for dealing with the offence in question",
  "type": "object",
  "properties": {
    "originatingHearingId": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "offenceId": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "motReasonId": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "motReasonDescription": {
      "type": "string"
    },
    "motReasonCode": {
      "type": "string"
    },
    "allocationDecisionDate": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
    },
    "courtIndicatedSentence": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtIndicatedSentence.json#"
    },
    "sequenceNumber": {
      "type": "integer"
    }
  },
  "required": [
    "offenceId",
    "motReasonId",
    "motReasonDescription",
    "motReasonCode",
    "sequenceNumber"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/allocation_decision.json
{
  "originatingHearingId": "7084b980-d09d-40bc-b856-ea1fafd401bf",
  "offenceId": "e58b3a59-e5e5-4ec4-a478-2c846b9e6b6d",
  "motReasonId": "d47268e9-db2e-3aa3-827b-ba3afb7ff94a",
  "motReasonDescription": "Court directs trial by jury",
  "motReasonCode": "5",
  "sequenceNumber": 20,
  "allocationDecisionDate": "2020-02-13",
  "courtIndicatedSentence": {
    "courtIndicatedSentenceTypeId": "f7f76e0b-366b-4746-b0b0-4d8a46c6ad4e",
    "courtIndicatedSentenceDescription": "Aut laborum quia et."
  }
}
