=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/apiCourtApplicationType.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiCourtApplicationType.json",
  "description": "The type of application made to court for judicial decision. Taken from reference data",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "code": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "legislation": {
      "type": "string"
    },
    "categoryCode": {
      "type": "string"
    },
    "linkType": {
      "type": "string",
      "enum": [
        "STANDALONE",
        "LINKED",
        "SJP",
        "FIRST_HEARING"
      ]
    },
    "jurisdiction": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/applicationJurisdictionType"
    },
    "appealFlag": {
      "type": "boolean"
    },
    "summonsTemplateType": {
      "type": "string",
      "enum": [
        "GENERIC_APPLICATION",
        "BREACH",
        "NOT_APPLICABLE",
        "FIRST_HEARING",
        "PARENT_GENERIC_CASE"
      ]
    },
    "validFrom": {
      "type": "string",
      "format": "date"
    },
    "validTo": {
      "type": "string",
      "format": "date"
    },
    "applicantAppellantFlag": {
      "type": "boolean"
    },
    "pleaApplicableFlag": {
      "type": "boolean"
    },
    "offenceActiveOrder": {
      "type": "string",
      "enum": [
        "OFFENCE",
        "COURT_ORDER",
        "NOT_APPLICABLE"
      ]
    },
    "commrOfOathFlag": {
      "type": "boolean"
    },
    "breachType": {
      "type": "string",
      "enum": [
        "GENERIC_BREACH",
        "COMMISSION_OF_NEW_OFFENCE_BREACH",
        "NOT_APPLICABLE"
      ]
    },
    "courtOfAppealFlag": {
      "type": "boolean"
    },
    "courtExtractAvlFlag": {
      "type": "boolean"
    },
    "listingNotifTemplate": {
      "type": "string"
    },
    "boxworkNotifTemplate": {
      "type": "string"
    },
    "typeWelsh": {
      "type": "string"
    },
    "legislationWelsh": {
      "type": "string"
    },
    "prosecutorThirdPartyFlag": {
      "type": "boolean"
    },
    "spiOutApplicableFlag": {
      "type": "boolean"
    },
    "hearingCode": {
      "type": "string"
    },
    "resentencingActivationCode": {
      "type": "string"
    },
    "prefix": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "type",
    "categoryCode",
    "linkType",
    "jurisdiction",
    "summonsTemplateType",
    "breachType",
    "appealFlag",
    "applicantAppellantFlag",
    "pleaApplicableFlag",
    "commrOfOathFlag",
    "courtOfAppealFlag",
    "courtExtractAvlFlag",
    "prosecutorThirdPartyFlag",
    "spiOutApplicableFlag",
    "offenceActiveOrder"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/court_application_type/all_fields.json
{
  "id": "74b72f6f-414a-3464-a4a2-d91397b4c439",
  "appealFlag": true,
  "applicantAppellantFlag": false,
  "boxworkNotifTemplate": "NOT_APPLICABLE",
  "breachType": "NOT_APPLICABLE",
  "categoryCode": "CO",
  "code": "MC80801",
  "commrOfOathFlag": false,
  "courtExtractAvlFlag": true,
  "courtOfAppealFlag": false,
  "hearingCode": "APN",
  "jurisdiction": "EITHER",
  "legislation": "Pursuant to Regulation 14 of the Criminal Legal Aid",
  "linkType": "LINKED",
  "listingNotifTemplate": "POSTAL_NOTIFICATION",
  "offenceActiveOrder": "NOT_APPLICABLE",
  "pleaApplicableFlag": false,
  "prosecutorThirdPartyFlag": false,
  "spiOutApplicableFlag": true,
  "summonsTemplateType": "NOT_APPLICABLE",
  "type": "Appeal against conviction and sentence by a Magistrates' Court to the Crown Court",
  "validFrom": "2022-01-01"
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/court_application_type/required_fields.json
{
  "id": "74b72f6f-414a-3464-a4a2-d91397b4c439",
  "type": "Appeal against conviction and sentence by a Magistrates' Court to the Crown Court",
  "code": "MC80801",
  "categoryCode": "CO",
  "linkType": "LINKED",
  "jurisdiction": "EITHER",
  "summonsTemplateType": "NOT_APPLICABLE",
  "breachType": "NOT_APPLICABLE",
  "appealFlag": false,
  "applicantAppellantFlag": false,
  "pleaApplicableFlag": false,
  "commrOfOathFlag": false,
  "courtOfAppealFlag": false,
  "courtExtractAvlFlag": true,
  "prosecutorThirdPartyFlag": false,
  "spiOutApplicableFlag": true,
  "offenceActiveOrder": "NOT_APPLICABLE"
}
