=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/apiLaaReference.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiLaaReference.json",
  "type": "object",
  "description": "The status of an application for legal aid funding",
  "properties": {
    "applicationReference": {
      "description": "The human readable reference to the application supplied by legal aid agency",
      "type": "string"
    },
    "statusId": {
      "description": "Reference data identifer for the agreed status",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "statusCode": {
      "description": "The status code from reference data",
      "type": "string"
    },
    "statusDescription": {
      "description": "The status description from reference data",
      "type": "string"
    },
    "statusDate": {
      "description": "The date that the status was recorded",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
    },
    "effectiveStartDate": {
      "description": "The start date for legal aid, set when the status represents an approved representation order",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
    },
    "effectiveEndDate": {
      "description": "The end date for legal aid, set when the status represents an approved representation order",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
    },
    "offenceLevelStatus": {
      "description": "The defendant level status coming from legal status ref data table",
      "type": "string"
    },
    "laaContractNumber": {
      "description": "this will be null when LAA reference is recorded and will be set when representation order is received",
      "type": "string"
    }
  },
  "required": [
    "applicationReference",
    "statusId",
    "statusCode",
    "statusDescription",
    "statusDate"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/laa_reference/all_fields.json
{
  "applicationReference": "A10000099",
  "statusId": "38944fbb-c8a6-45ff-9b5c-e09e9867eabc",
  "statusCode": "AP",
  "statusDescription": "LAA status description",
  "statusDate": "2020-11-05",
  "effectiveStartDate": "2021-04-10",
  "effectiveEndDate": "2021-04-11",
  "laaContractNumber": "27900"
}
