=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/apiLesserOrAlternativeOffence.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiLesserOrAlternativeOffence.json",
  "description": "The details of a lesserOrAlternativeOffence verdict",
  "type": "object",
  "properties": {
    "offenceDefinitionId": {
      "description": "The identifier of the offence from reference data",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "offenceCode": {
        "type": "string"
    },
    "offenceTitle": {
        "type": "string"
    },
    "offenceTitleWelsh": {
        "type": "string"
    },
    "offenceLegislation": {
        "type": "string"
    },
    "offenceLegislationWelsh": {
        "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "offenceDefinitionId",
    "offenceCode",
    "offenceTitle",
    "offenceLegislation"
  ]
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/lesser_or_alternative_offence/all_fields.json
{
  "offenceDefinitionId": "62bbc890-1e3e-4b98-b2fe-107d07f75259",
  "offenceCode": "AAA",
  "offenceTitle": "Drunkenness in a public place",
  "offenceTitleWelsh": "Meddwdod mewn man cyhoeddus",
  "offenceLegislation": "Criminal Justice Act 1967",
  "offenceLegislationWelsh": "Deddf Cyfiawnder Troseddol 1967"
}
