=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/apiOrganisation.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiOrganisation.json",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the organisation",
      "type": "string"
    },
    "incorporationNumber": {
      "description": "The incorporation details of teh organisationorganisation",
      "type": "string"
    },
    "registeredCharityNumber": {
      "description": "The registered charity details",
      "type": "string"
    },
    "address": {
      "description": "The organisation address details",
      "$ref": "http://justice.gov.uk/core/courts/external/apiAddress.json"
    },
    "contact": {
      "description": "The organisation contact details",
      "$ref": "http://justice.gov.uk/core/courts/external/apiContactNumber.json"
    }
  },
  "required": [
    "name"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/organisation.json
{
  "name": "The Johnson Partnership",
  "incorporationNumber": "1234",
  "registeredCharityNumber": "5678",
  "address": {
    "address1": "104",
    "address2": "Fleet Street",
    "address3": "Westminster",
    "address4": "London",
    "address5": "GB",
    "postcode": "EC4A 2AH"
  },
  "contact": {
    "home": "1-867-889-0000",
    "work": "1-893-936-0000",
    "mobile": "640-287-0000",
    "primaryEmail": "primary@example.com",
    "secondaryEmail": "secondary@example.com",
    "fax": "1-275-412-9791 x8048"
  }
}
