=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/apiPersonDefendant.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiPersonDefendant.json",
  "type": "object",
  "properties": {
    "personDetails": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiPerson.json"
    },
    "bailStatus": {
      "description": "The defendant bail status for the given case",
      "$ref": "http://justice.gov.uk/core/courts/external/apiBailStatus.json"
    },
    "bailConditions": {
      "description": "Defines the conditions that have been applied to the Order of Bail, or Order of Remand into the care of the Local Authority",
      "type": "string"
    },
    "bailReasons": {
      "description": "Defines the reasons for setting bail conditions or the reasons for custody",
      "type": "string"
    },
    "custodyTimeLimit": {
      "description": "The custody time limit for the given case when the bail status is remanded-in-custody",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
    },
    "perceivedBirthYear": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/positiveInteger"
    },
    "driverNumber": {
      "type": "string"
    },
    "driverLicenceCode": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/driverLicenseCode"
    },
    "driverLicenseIssue": {
      "description": "identifies the license issue no.",
      "type": "string"
    },
    "vehicleOperatorLicenceNumber": {
      "description": "You need an operator's licence to operate vehicles above 3.5 tonnes gross vehicle weight (gvw) that are used to carry goods (ie anything not permanently attached to the vehicle) on public roads for trade or business purposes.",
      "type": "string"
    },
    "arrestSummonsNumber": {
      "type": "string"
    },
    "employerOrganisation": {
      "$ref": "http://justice.gov.uk/core/courts/external/apiOrganisation.json"
    },
    "employerPayrollReference": {
      "type": "string"
    }
  },
  "required": [
    "personDetails"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/person_defendant.json
{
  "arrestSummonsNumber": "TFL1",
  "bailConditions": "some conditions",
  "bailStatus": {
    "code": "C",
    "description": "Custody or remanded into custody",
    "id": "12e69486-4d01-3403-a50a-7419ca040635"
  },
  "personDetails": {
    "nationalInsuranceNumber": "AA123456C",
    "address": {
      "address1": "Address Line 1",
      "address2": "Address Line 2",
      "address3": "Address Line 3",
      "address4": "Address Line 4",
      "address5": "Address Line 5",
      "postcode": "SW1H 9EA"
    },
    "contact": {
      "home": "000-000-0000",
      "work": "111-111-1111",
      "mobile": "222-222-2222",
      "primaryEmail": "primary@example.com",
      "secondaryEmail": "secondary@example.com"
    },
    "dateOfBirth": "1990-01-01",
    "documentationLanguageNeeds": "WELSH",
    "firstName": "Carlee",
    "middleName": "Williamson",
    "lastName": "Connelly",
    "gender": "MALE",
    "title": "Mr"
  }
}
