=== ministryofjustice/laa-court-data-adaptor/docs/schemas_common_platform_court_applications/global_2/apiPerson.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/external/apiPerson.json",
  "type": "object",
  "properties": {
    "title": {
      "description": "The person title",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/personTitle"
    },
    "firstName": {
      "description": "The person fore name",
      "type": "string"
    },
    "middleName": {
      "description": "The person middle name",
      "type": "string"
    },
    "lastName": {
      "description": "The person last name",
      "type": "string"
    },
    "dateOfBirth": {
      "description": "The person date of birth",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
    },
    "nationalityId": {
      "description": "The person nationality identifier from reference data",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "nationalityCode": {
      "description": "The person nationality code based on reference data",
      "type": "string"
    },
    "nationalityDescription": {
      "description": "The person nationality description based on reference data",
      "type": "string"
    },
    "additionalNationalityId": {
      "description": "The person nationality identifier from reference data",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
    },
    "additionalNationalityCode": {
      "description": "The person additional nationality code based on reference data",
      "type": "string"
    },
    "additionalNationalityDescription": {
      "description": "The person additional nationality description based on reference data",
      "type": "string"
    },
    "disabilityStatus": {
      "description": "The person disability status",
      "type": "string"
    },
    "ethnicity": {
      "description": "The person ethnicity details",
      "$ref": "http://justice.gov.uk/core/courts/external/apiEthnicity.json#"
    },
    "gender": {
      "description": "The person gender",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/gender"
    },
    "interpreterLanguageNeeds": {
      "description": "The person interpreter needs",
      "type": "string"
    },
    "documentationLanguageNeeds": {
      "description": "The person documentation needs.  Indicates the requirement for documentation to be published in non English",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/hearingLanguage"
    },
    "nationalInsuranceNumber": {
      "description": "The person nino",
      "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/nino"
    },
    "occupation": {
      "description": "The person occupation",
      "type": "string"
    },
    "occupationCode": {
      "description": "The person occupation code",
      "type": "string"
    },
    "specificRequirements": {
      "description": "The person special needs indicted any special needs that must be met by the courts process e.g. wheelchair access",
      "type": "string"
    },
    "address": {
      "description": "The person address details",
      "$ref": "http://justice.gov.uk/core/courts/external/apiAddress.json"
    },
    "contact": {
      "description": "The person contact details",
      "$ref": "http://justice.gov.uk/core/courts/external/apiContactNumber.json"
    }
  },
  "required": [
    "lastName",
    "gender"
  ],
  "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/person.json
{
  "address": {
    "address1": "5 Privet Drive",
    "address2": "Darlington",
    "postcode": "DL8 8FJ"
  },
  "dateOfBirth": "1965-11-30",
  "documentationLanguageNeeds": "ENGLISH",
  "ethnicity": {
    "observedEthnicityCode": "1",
    "observedEthnicityDescription": "White",
    "observedEthnicityId": "c4ca4238-a0b9-3382-8dcc-509a6f75849b",
    "selfDefinedEthnicityCode": "W1",
    "selfDefinedEthnicityDescription": "British",
    "selfDefinedEthnicityId": "c4ca4238-a0b9-3382-8dcc-509a6f75849b"
  },
  "firstName": "John",
  "gender": "MALE",
  "lastName": "Smith",
  "occupation": "Unemployed",
  "occupationCode": "6001",
  "title": "Mr"
}
