=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/search/apiDefendantSummary.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://justice.gov.uk/core/courts/search/external/apiDefendantSummary.json",
    "description": "A summary of defendant details",
    "type": "object",
    "properties": {
        "defendantId": {
            "description": "The identifier of the defendant",
            "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
        },
        "defendantNINO": {
          "description": "The person nino when the defendant is a person",
          "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/nino"
        },
        "defendantASN": {
          "description": "The police arrest summons number when the defendant is a person",
          "type": "string"
        },
        "defendantName": {
          "description": "The name of the defendant",
          "type": "string"
        },
        "defendantDOB": {
          "description": "The person date of birth when the defendant is a person",
          "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
        },
        "dateOfNextHearing": {
          "description": "The date of the next hearing for the defendant",
          "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/datePattern"
        },
        "proceedingsConcluded": {
          "description": "Indicates that proceedings for the defendant have been conckuded i.e. all offences have been disposed with final results or have been withdrawn by the prosecuting authority",
          "type": "boolean"
        },
        "offenceSummary": {
            "description": "The offences for this defendant",
            "type": "array",
            "minItems": 1,
            "items": {
             "$ref": "http://justice.gov.uk/core/courts/search/external/apiOffenceSummary.json"
            }
        }
    },
    "required": [
        "defendantId",
        "defendantName",
        "offenceSummary"
    ],
    "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/defendant_summary/all_fields.json
{
  "proceedingsConcluded": false,
  "defendantId": "b760daba-0d38-4bae-ad57-fbfd8419aefe",
  "defendantASN": "2100000000000267128K",
  "defendantName": "Bob Steven Smith",
  "defendantDOB": "1986-11-10",
  "defendantNINO": "AA123456C",
  "offenceSummary": [
    {
      "offenceId": "9aca847f-da4e-444b-8f5a-2ce7d776ab75",
      "offenceCode": "TH68026C",
      "offenceTitle": "Conspire to commit a burglary dwelling with    intent to steal",
      "offenceLegislation": "Contrary to section 1(1) of the    Criminal Law Act 1977.",
      "proceedingsConcluded": false,
      "arrestDate": "2021-03-23",
      "startDate": "2021-03-06",
      "chargeDate": "2021-03-24",
      "modeOfTrial": "Indictable",
      "orderIndex": 1,
      "wording": "Between 06.03.2021 and 22.03.2021 at DERBY in the county of DERBYSHIRE, conspired together with John Doe to enter as a trespasser, a number of dwellings within the CHADDESDEN and LITTLEOVER areas of DERBY, with intent to steal therein\n'Contrary to section 1(1) of the Criminal Law Act 1977.'\n -- CCCJS CODE: 'TH68026C'",
      "laaApplnReference": {
        "applicationReference": "LAA-552244",
        "statusId": "04741935-488e-4c1a-bf81-cf20a7562b23",
        "statusCode": "1",
        "statusDescription": "description",
        "statusDate": "2021-04-09"
      }
    },
    {
      "offenceId": "4a852bd1-0068-422c-994f-78a5373ecd75",
      "offenceCode": "CJ88149",
      "offenceTitle": "Assault by beating of an emergency worker",
      "offenceLegislation": "Contrary to section 39 of the Criminal Justice Act 1988 and section 1 of the Assaults on Emergency Workers (Offences) Act 2018.",
      "proceedingsConcluded": false,
      "arrestDate": "2021-03-23",
      "startDate": "2021-03-23",
      "chargeDate": "2021-03-24",
      "modeOfTrial": "Either Way",
      "orderIndex": 2,
      "wording": "On 23.03.2021 at DERBY in the county of DERBYSHIRE assaulted an emergency worker, namely Police Constable, acting in the exercise of his functions as such a worker, by beating him\n'Contrary to section 39 of the Criminal Justice Act 1988 and section 1 of the Assaults on Emergency Workers (Offences) Act 2018.'\n -- CCCJS CODE: 'CJ88149'",
      "laaApplnReference": {
        "applicationReference": "LAA-552244",
        "statusId": "c744dfc5-1f22-486b-a749-2502e73fa5be",
        "statusCode": "1",
        "statusDescription": "description",
        "statusDate": "2021-04-11"
      }
    }
  ]
}
