=== ministryofjustice/laa-court-data-adaptor/lib/schemas/global/search/apiProsecutionCaseSummary.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://justice.gov.uk/core/courts/search/external/apiProsecutionCaseSummary.json",
    "description": "A summary of a prosecution case",
    "type": "object",
    "properties": {
        "prosecutionCaseId": {
            "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/uuid"
        },
        "prosecutionCaseReference": {
            "description": "The prosecuting authorities reference for their prosecution case that is layed before court.  For example PTI-URN from police/cps cases",
            "type": "string"
        },
        "caseStatus": {
            "description": "The status of the case.  When SJP Referrals are received or when court proceedings are initialised this will be set to ACTIVE by the receiving Progression API",
            "$ref": "http://justice.gov.uk/core/courts/external/apiCourtsDefinitions.json#/definitions/prosecutionCaseStatus"
        },
        "defendantSummary": {
            "description": "The defendants accused on the prosecution case",
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "http://justice.gov.uk/core/courts/search/external/apiDefendantSummary.json"
            }
        },
        "hearingSummary": {
            "description": "The court proceedings for the prosecution case",
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "http://justice.gov.uk/core/courts/search/external/apiHearingSummary.json"
            }
        }
    },
    "required": [
        "prosecutionCaseId",
        "prosecutionCaseReference",
        "caseStatus",
        "defendantSummary"
    ],
    "additionalProperties": false
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/prosecution_case_summary/all_fields.json
{
  "caseStatus": "ACTIVE",
  "prosecutionCaseId": "46def95e-3088-4e8c-b7c9-83b2208f7800",
  "prosecutionCaseReference": "30DI0570888",
  "defendantSummary": [
    {
      "proceedingsConcluded": false,
      "defendantId": "b760daba-0d38-4bae-ad57-fbfd8419aefe",
      "defendantASN": "2100000000000267128K",
      "defendantName": "Bob Steven Smith",
      "defendantDOB": "1986-11-10",
      "defendantNINO": "AA123456C",
      "offenceSummary": [
        {
          "offenceId": "9aca847f-da4e-444b-8f5a-2ce7d776ab75",
          "offenceCode": "TH68026C",
          "offenceTitle": "Conspire to commit a burglary dwelling with intent to steal",
          "offenceLegislation": "Contrary to section 1(1) of the    Criminal Law Act 1977.",
          "proceedingsConcluded": false,
          "arrestDate": "2021-03-23",
          "startDate": "2021-03-06",
          "chargeDate": "2021-03-24",
          "modeOfTrial": "Indictable",
          "orderIndex": 1,
          "wording": "In the county of DERBYSHIRE, conspired together with John Doe to enter as a trespasser",
          "laaApplnReference": {
            "statusId": "18e86937-9652-32a3-a9fb-dbd01eda86a5",
            "statusCode": "GR",
            "statusDescription": "Granted (One Advocate)",
            "statusDate": "2021-05-02",
            "applicationReference": "6960540"
          }
        },
        {
          "offenceId": "4a852bd1-0068-422c-994f-78a5373ecd75",
          "offenceCode": "CJ88149",
          "offenceTitle": "Assault by beating of an emergency worker",
          "offenceLegislation": "Contrary to section 39 of the Criminal Justice Act 1988 and section 1 of the Assaults on Emergency Workers (Offences) Act 2018.",
          "proceedingsConcluded": false,
          "arrestDate": "2021-03-23",
          "startDate": "2021-03-23",
          "chargeDate": "2021-03-24",
          "modeOfTrial": "Either Way",
          "orderIndex": 2,
          "wording": "On 23.05.2021 at DERBY in the county of DERBYSHIRE assaulted an emergency worker, namely Police Constable",
          "laaApplnReference": {
            "statusId": "18e86937-9652-32a3-a9fb-dbd01eda86a5",
            "statusCode": "GR",
            "statusDescription": "Granted (One Advocate)",
            "statusDate": "2021-05-02",
            "applicationReference": "6960540"
          }
        }
      ]
    },
    {
      "proceedingsConcluded": false,
      "defendantId": "562dc2de-2258-4476-8be4-69cf15623f83",
      "defendantASN": "2100000000000266764M",
      "defendantName": "Bob Steven Smith",
      "defendantDOB": "1992-07-27",
      "offenceSummary": [
        {
          "offenceId": "a6437f6a-bdac-44ca-898a-486bdacc9625",
          "offenceCode": "TH68026C",
          "offenceTitle": "Conspire to commit a burglary dwelling with intent to steal",
          "offenceLegislation": "Contrary to section 1(1) of the Criminal Law Act 1977.",
          "proceedingsConcluded": false,
          "arrestDate": "2021-03-23",
          "startDate": "2021-03-06",
          "chargeDate": "2021-03-24",
          "modeOfTrial": "Indictable",
          "orderIndex": 1,
          "wording": "Between 06.03.2021 and 22.03.2021 at DERBY in the county of DERBYSHIRE, conspired together with Harry Potter to enter as a trespasser, a number of dwellings within the CHADDESDEN and LITTLEOVER areas of DERBY, with intent to steal therein\n'Contrary to section 1(1) of the Criminal Law Act 1977.'\n -- CCCJS CODE: 'TH68026C'",
          "laaApplnReference": {
            "statusId": "18e86937-9652-32a3-a9fb-dbd01eda86a5",
            "statusCode": "GR",
            "statusDescription": "Granted (One Advocate)",
            "statusDate": "2021-05-02",
            "applicationReference": "6960540"
          }
        }
      ]
    }
  ],
  "hearingSummary": [
    {
      "hearingId": "9b8df2aa-802d-413a-82b3-89eff25cde7b",
      "jurisdictionType": "MAGISTRATES",
      "defendantIds": [
        "562dc2de-2258-4476-8be4-69cf15623f83",
        "b760daba-0d38-4bae-ad57-fbfd8419aefe"
      ],
      "hearingDays": [
        {
          "sittingDay": "2021-03-25T09:30:00.000Z",
          "listingSequence": 8,
          "listedDurationMinutes": 20
        }
      ],
      "hearingType": {
        "id": "4a0e892d-c0c5-3c51-95b8-704d8c781776",
        "description": "First hearing"
      },
      "courtCentre": {
        "id": "14876ea1-5f7c-32ef-9fbd-aa0b63193550",
        "name": "Derby Justice Centre (aka Derby St Mary Adult)",
        "roomId": "2fc95ce0-79e5-33c6-901a-733c90905e59",
        "roomName": "Courtroom 08",
        "code": "B30PI00"
      }
    },
    {
      "hearingId": "2816b8d4-f141-4c39-82fc-a98c6fb3fcfa",
      "jurisdictionType": "CROWN",
      "defendantIds": [
        "b760daba-0d38-4bae-ad57-fbfd8419aefe",
        "562dc2de-2258-4476-8be4-69cf15623f83"
      ],
      "hearingDays": [
        {
          "sittingDay": "2021-05-20T09:30:00.000Z",
          "listingSequence": 4,
          "listedDurationMinutes": 30
        }
      ],
      "hearingType": {
        "id": "06b0c2bf-3f98-46ed-ab7e-56efaf9ecced",
        "description": "Plea and Trial Preparation"
      },
      "courtCentre": {
        "id": "6131bd34-33d9-3d1e-8152-8b5a2084f1bd",
        "name": "Derby Crown Court",
        "roomId": "594d6332-9806-38ab-830d-5941e671e0bb",
        "roomName": "Courtroom 01",
        "code": "C30DE00"
      }
    }
  ]
}

=== ministryofjustice/laa-court-data-adaptor/spec/fixtures/files/prosecution_case_summary/required_fields.json
{
  "caseStatus": "ACTIVE",
  "prosecutionCaseId": "46def95e-3088-4e8c-b7c9-83b2208f7800",
  "prosecutionCaseReference": "30DI0570888",
  "defendantSummary": [
    {
      "proceedingsConcluded": false,
      "defendantId": "b760daba-0d38-4bae-ad57-fbfd8419aefe",
      "defendantASN": "2100000000000267128K",
      "defendantName": "Bob Steven Smith",
      "defendantDOB": "1986-11-10",
      "defendantNINO": "AA123456C",
      "offenceSummary": [
        {
          "offenceId": "9aca847f-da4e-444b-8f5a-2ce7d776ab75",
          "offenceCode": "TH68026C",
          "offenceTitle": "Conspire to commit a burglary dwelling with intent to steal",
          "offenceLegislation": "Contrary to section 1(1) of the    Criminal Law Act 1977.",
          "proceedingsConcluded": false,
          "arrestDate": "2021-03-23",
          "startDate": "2021-03-06",
          "chargeDate": "2021-03-24",
          "modeOfTrial": "Indictable",
          "orderIndex": 1,
          "wording": "In the county of DERBYSHIRE, conspired together with John Doe to enter as a trespasser",
          "laaApplnReference": {
            "statusId": "18e86937-9652-32a3-a9fb-dbd01eda86a5",
            "statusCode": "GR",
            "statusDescription": "Granted (One Advocate)",
            "statusDate": "2021-05-02",
            "applicationReference": "6960540"
          }
        },
        {
          "offenceId": "4a852bd1-0068-422c-994f-78a5373ecd75",
          "offenceCode": "CJ88149",
          "offenceTitle": "Assault by beating of an emergency worker",
          "offenceLegislation": "Contrary to section 39 of the Criminal Justice Act 1988 and section 1 of the Assaults on Emergency Workers (Offences) Act 2018.",
          "proceedingsConcluded": false,
          "arrestDate": "2021-03-23",
          "startDate": "2021-03-23",
          "chargeDate": "2021-03-24",
          "modeOfTrial": "Either Way",
          "orderIndex": 2,
          "wording": "On 23.05.2021 at DERBY in the county of DERBYSHIRE assaulted an emergency worker, namely Police Constable",
          "laaApplnReference": {
            "statusId": "18e86937-9652-32a3-a9fb-dbd01eda86a5",
            "statusCode": "GR",
            "statusDescription": "Granted (One Advocate)",
            "statusDate": "2021-05-02",
            "applicationReference": "6960540"
          }
        }
      ]
    },
    {
      "proceedingsConcluded": false,
      "defendantId": "562dc2de-2258-4476-8be4-69cf15623f83",
      "defendantASN": "2100000000000266764M",
      "defendantName": "John Doe",
      "defendantDOB": "1992-07-27",
      "offenceSummary": [
        {
          "offenceId": "a6437f6a-bdac-44ca-898a-486bdacc9625",
          "offenceCode": "TH68026C",
          "offenceTitle": "Conspire to commit a burglary dwelling with intent to steal",
          "offenceLegislation": "Contrary to section 1(1) of the Criminal Law Act 1977.",
          "proceedingsConcluded": false,
          "arrestDate": "2021-03-23",
          "startDate": "2021-03-06",
          "chargeDate": "2021-03-24",
          "modeOfTrial": "Indictable",
          "orderIndex": 1,
          "wording": "Between 06.03.2021 and 22.03.2021 at DERBY in the county of DERBYSHIRE, conspired together with Harry Potter to enter as a trespasser, a number of dwellings within the CHADDESDEN and LITTLEOVER areas of DERBY, with intent to steal therein\n'Contrary to section 1(1) of the Criminal Law Act 1977.'\n -- CCCJS CODE: 'TH68026C'",
          "laaApplnReference": {
            "applicationReference": "6960540",
            "statusId": "98e86937-9652-32a3-a9fb-dbd01eda86a5",
            "statusCode": "GR",
            "statusDescription": "Granted (One Advocate)",
            "statusDate": "2021-05-02"
          }
        }
      ]
    }
  ]
}
